# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker Test 1

jhipster:
  security:
    authentication:
      jwt:
        secret: my-secret-key-which-should-be-1111changed-in-production-and-be-base64-encoded

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
