version: '2.4'
services:
  analyticservice-app:
    image: analyticservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=analyticservice-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ms-network
  analyticservice-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: analyticservice-cassandra
    networks:
      - ms-network
  analyticservice-cassandra-node:
    image: cassandra:3.11.4
    environment:
      - CASSANDRA_SEEDS=analyticservice-cassandra
    networks:
      - ms-network
  analyticservice-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: analyticservice-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    networks:
      - ms-network

networks:
  ms-network:
    name: my-app-net