version: '2.4'
services:
  analyticservice-cassandra:
    image: cassandra:3.11.4
    # volumes:
    #     - ~/volumes/jhipster/AnalyticService/cassandra/:/var/lib/cassandra/data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  analyticservice-cassandra-node:
    image: cassandra:3.11.4
    environment:
      - CASSANDRA_SEEDS=analyticservice-cassandra
  analyticservice-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: analyticservice-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
