version: '2.4'
services:
  statsservice-app:
    image: statsservice
    networks:
      - network1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://statsservice-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=StatsService
      - JHIPSTER_SLEEP=5 # gives time for other services to boot before the application
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
  statsservice-mongodb:
    extends:
      file: mongodb.yml
      service: statsservice-mongodb
    networks:
      - network1
    ports:
      - 27017:27017
      
networks:
    network1:
        name: my-app-net