version: '2'
services:
  accountservice-mongodb:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
    command: mongos --configdb accountservice-mongodb-config
  accountservice-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  accountservice-mongodb-config:
    image: mongo:4.0.10
    container_name: accountservice-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
